// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ArchitectController from "./architect_controller"
application.register("architect", ArchitectController)

import ComposerController from "./composer_controller"
application.register("composer", ComposerController)

import GrandmotherController from "./grandmother_controller"
application.register("grandmother", GrandmotherController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PlayerController from "./player_controller"
application.register("player", PlayerController)

import ScorecardController from "./scorecard_controller"
application.register("scorecard", ScorecardController)
