// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import GrandmotherController from "./grandmother_controller"
application.register("grandmother", GrandmotherController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ReporterController from "./reporter_controller"
application.register("reporter", ReporterController)
